spring.application.name=JournalApp


spring.datasource.url = jdbc:mysql://localhost:3306/DB_name
spring.datasource.username = root
spring.datasource.password = 301206

spring.datasource.driver = com.mysql.cj.jd
